language: c

compiler:
    - clang
    - gcc

before_script:
    - sudo apt-get install gperf

script:
    - [[ $CC == "clang" ]] && CC=`which clang`
    - [[ $CXX == "clang++" ]] && CXX=`which clang++`
    - scons -Q
    - src/all_test
    - cd src && ./yamada --test testing/all_test.ymd
