language: c

compiler:
    - clang
    - gcc

before_script:
    - sudo apt-get install gperf

script:
    - if [[ $CC == "clang" ]]; then export CC=`which clang`; fi
    - if [[ $CXX == "clang++" ]]; then export CXX=`which clang++`; fi
    - scons -Q
    - src/all_test
    - cd src && ./yamada --test testing/all_test.ymd
